#!/bin/bash
#
# Test the PostgreSQL image in OpenShift (remote cluster)
#
# IMAGE_NAME specifies a name of the candidate image used for testing.
# The image has to be available before this script is executed.
# VERSION specifies the major version of the PostgreSQL in format of X.Y
# OS specifies RHEL version (e.g. OS=rhel7)
#

THISDIR=$(dirname ${BASH_SOURCE[0]})

source ${THISDIR}/test-lib-postgresql.sh

set -eo nounset

trap ct_os_cleanup EXIT SIGINT

ct_os_set_ocp4

ct_os_check_compulsory_vars

oc status || false "It looks like oc is not properly logged in."

# For testing on OpenShift 4 we use internal registry
export CT_OCP4_TEST=true

# Check the template
test_postgresql_integration "${IMAGE_NAME}"

# Check the imagestream
test_postgresql_imagestream

OS_TESTSUITE_RESULT=0

# vim: set tabstop=2:shiftwidth=2:expandtab:

