FROM {{ spec.minimal_image }}

# PostgreSQL image for OpenShift.
# Volumes:
#  * /var/lib/pgsql/data   - Database cluster for PostgreSQL
# Environment:
#  * $POSTGRESQL_USER     - Database user name
#  * $POSTGRESQL_PASSWORD - User's password
#  * $POSTGRESQL_DATABASE - Name of the database to create
#  * $POSTGRESQL_ADMIN_PASSWORD (Optional) - Password for the 'postgres'
#                           PostgreSQL administrative account

ENV POSTGRESQL_VERSION={{ spec.version }} \
    {% if spec.prod in ["c11s", "rhel11"] %}
    POSTGRESQL_PREV_VERSION={{ spec.prev_version }} \
    {% endif %}
    HOME=/var/lib/pgsql \
    PGUSER=postgres \
    # Path to be used in other layers to place s2i scripts into
    STI_SCRIPTS_PATH=/usr/libexec/s2i \
    HOME=/opt/app-root/src \    
    APP_DATA=/opt/app-root

ENV SUMMARY="PostgreSQL is an advanced Object-Relational database management system" \
    DESCRIPTION="PostgreSQL is an advanced Object-Relational database management system (DBMS). \
The image contains the client and server programs that you'll need to \
create, run, maintain and access a PostgreSQL DBMS server."

LABEL summary="$SUMMARY" \
      description="$DESCRIPTION" \
      io.k8s.description="$DESCRIPTION" \
      io.k8s.display-name="PostgreSQL {{ spec.version }}" \
      io.openshift.expose-services="5432:postgresql" \
      io.openshift.tags="{{ spec.openshift_tags }}" \
      io.openshift.s2i.assemble-user="26" \
      name="{{ spec.org }}/postgresql-{{ spec.short }}-minimal{% if spec.org == "sclorg" %}-{{ spec.prod }}{% endif %}" \
      com.redhat.component="{{ spec.redhat_component }}" \
{% if spec.prod in ["c11s"] %}
      version="1" \
{% endif %}
{% if config.os.id == 'rhel' %}
      com.redhat.license_terms="https://www.redhat.com/en/about/red-hat-end-user-license-agreements#rhel" \
{% endif %}
      usage="podman run -d --name postgresql_database -e POSTGRESQL_USER=user -e POSTGRESQL_PASSWORD=pass -e POSTGRESQL_DATABASE=db -p 5432:5432 {{ spec.org }}/postgresql-{{ spec.short }}-minimal{% if spec.org == "sclorg" %}-{{ spec.prod }}{% endif %}" \
      maintainer="SoftwareCollections.org <sclorg@redhat.com>"

EXPOSE 5432

COPY root/usr/libexec/fix-permissions /usr/libexec/fix-permissions

# This image must forever use UID 26 for postgres user so our volumes are
# safe in the future. This should *never* change, the last test is there
# to make sure of that.
{% if spec.repo_enable_reason %}
{{ spec.repo_enable_reason }}
{% endif %}
{% if spec.prod in ["c10s", "rhel10", "c11s", "rhel11"] %}
RUN INSTALL_PKGS="rsync tar gettext-envsubst nss_wrapper-libs glibc-locale-source xz" && \
    PSQL_PKGS="{{ spec.pkgs }}" && \
{% endif %}
{% if spec.version == "18" or spec.prod in ["c10s", "rhel10", "c11s", "rhel11"] %}
    INSTALL_PKGS="$INSTALL_PKGS postgresql{{ spec.version }}-pgaudit" && \
{% endif %}
{% if spec.prod not in ["c10s", "rhel10", "c11s", "rhel11"] %}
    INSTALL_PKGS="$INSTALL_PKGS procps-ng util-linux postgresql-upgrade" && \
{% endif %}
{% if spec.version in ["18"] %}
    {% if spec.prod in ["c10s", "rhel10", "c11s", "rhel11"] %}
    PSQL_PKGS="$PSQL_PKGS postgresql{{ spec.version }}-pgvector" && \
    {% endif %}
{% endif %}
{% if spec.prod in ["c10s", "rhel10", "c11s", "rhel11"] %}
    microdnf -y --setopt=tsflags=nodocs install $INSTALL_PKGS $PSQL_PKGS  && \
    rpm -V $INSTALL_PKGS && \
{% endif %}
    postgres -V | grep -qe "$POSTGRESQL_VERSION\." && echo "Found VERSION $POSTGRESQL_VERSION" && \
    {% if spec.post_install %}
    {{ spec.post_install }}
    {% endif %}
    microdnf -y clean all --enablerepo='*' && \
    mkdir -p ${HOME}/.pki/nssdb && \
    chown -R 1001:0 ${HOME}/.pki && \    
    localedef -f UTF-8 -i en_US en_US.UTF-8 && \
    test "$(id postgres)" = "uid=26(postgres) gid=26(postgres) groups=26(postgres)" && \
    mkdir -p /var/lib/pgsql/data && \
    mkdir -p /run/postgresql && \
    /usr/libexec/fix-permissions /var/lib/pgsql /run/postgresql

# Get prefix path and path to scripts rather than hard-code them in scripts
ENV CONTAINER_SCRIPTS_PATH=/usr/share/container-scripts/postgresql

COPY root /
COPY ./s2i/bin/ $STI_SCRIPTS_PATH

# Hard links are not supported in Testing Farm approach during sync to guest
# operation system. Therefore tests are failing on error
# /usr/libexec/s2i/run no such file or directory
RUN ln -s /usr/bin/run-postgresql $STI_SCRIPTS_PATH/run


# S2I permission fixes
# --------------------
# 1. unless specified otherwise (or - equivalently - we are in OpenShift), s2i
#    build process would be executed as 'uid=26(postgres) gid=26(postgres)'.
#    Such process wouldn't be able to execute the default 'assemble' script
#    correctly (it transitively executes 'fix-permissions' script).  So let's
#    add the 'postgres' user into 'root' group here
#
# 2. we call fix-permissions on $APP_DATA here directly (UID=0 during build
#    anyways) to assure that s2i process is actually able to _read_ the
#    user-specified scripting.
RUN usermod -a -G root postgres && \
    /usr/libexec/fix-permissions --read-only "$APP_DATA"

USER 26

ENTRYPOINT ["container-entrypoint"]
CMD ["run-postgresql"]
