---
name: Imagestreamfiles check
on:
  issue_comment:
    types:
      - created

permissions:
  contents: read
  statuses: write

jobs:
  check:
    name: "Check imagestream generator generated files"
    runs-on: ubuntu-20.04
    if: |
      github.event.issue.pull_request
      && (contains(github.event.comment.body, '[test-openshift]') || contains(github.event.comment.body, '[test-all]'))
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)
    steps:
      - uses: sclorg/ci-scripts/ocp-stream-generator@master
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/head"
